"""
My First Person Game
Generated by ABS Engine
"""

from direct.showbase.ShowBase import ShowBase
from panda3d.core import Vec3, WindowProperties
from direct.task import Task
import json
import sys

class FirstPersonGame(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)

        # Load configuration
        try:
            with open('config.json', 'r') as f:
                self.config = json.load(f)
        except:
            print("Error: config.json not found!")
            sys.exit(1)

        # Set window properties
        props = WindowProperties()
        props.setTitle(self.config['title'])
        props.setSize(self.config['window_size'][0], self.config['window_size'][1])
        self.win.requestProperties(props)

        # Set background color
        bg = self.config['background_color']
        self.setBackgroundColor(bg[0], bg[1], bg[2])

        # Disable default mouse camera control
        self.disableMouse()

        # Player properties
        self.player_pos = Vec3(*self.config['player_start'])
        self.heading = 0
        self.pitch = 0
        self.move_speed = self.config['move_speed']
        self.mouse_sensitivity = self.config['mouse_sensitivity']

        # Set camera position
        self.camera.setPos(self.player_pos)
        self.camera.setHpr(self.heading, self.pitch, 0)

        # Movement keys
        self.keys = {
            'w': False,
            'a': False,
            's': False,
            'd': False,
            'space': False,
            'shift': False
        }

        self.setup_controls()
        self.create_scene()

        # Add movement task
        self.taskMgr.add(self.update, 'update')

        # Center and hide mouse
        props = WindowProperties()
        props.setCursorHidden(True)
        props.setMouseMode(WindowProperties.M_relative)
        self.win.requestProperties(props)

    def setup_controls(self):
        self.accept('w', self.set_key, ['w', True])
        self.accept('w-up', self.set_key, ['w', False])
        self.accept('a', self.set_key, ['a', True])
        self.accept('a-up', self.set_key, ['a', False])
        self.accept('s', self.set_key, ['s', True])
        self.accept('s-up', self.set_key, ['s', False])
        self.accept('d', self.set_key, ['d', True])
        self.accept('d-up', self.set_key, ['d', False])
        self.accept('space', self.set_key, ['space', True])
        self.accept('space-up', self.set_key, ['space', False])
        self.accept('shift', self.set_key, ['shift', True])
        self.accept('shift-up', self.set_key, ['shift', False])
        self.accept('escape', sys.exit)

    def set_key(self, key, value):
        self.keys[key] = value

    def create_scene(self):
        # Create objects from config
        for obj in self.config['objects']:
            if obj['type'] == 'cube':
                model = self.loader.loadModel('models/box')
            elif obj['type'] == 'sphere':
                model = self.loader.loadModel('models/sphere')
            elif obj['type'] == 'plane':
                model = self.loader.loadModel('models/box')
                model.setScale(obj['scale'] * 10, obj['scale'] * 10, 0.1)
                model.setPos(*obj['position'])
                model.reparentTo(self.render)
                continue

            model.setScale(obj['scale'])
            model.setPos(*obj['position'])
            model.reparentTo(self.render)

    def update(self, task):
        dt = globalClock.getDt()

        # Mouse look
        if self.mouseWatcherNode.hasMouse():
            md = self.win.getPointer(0)
            x = md.getX()
            y = md.getY()

            centerX = self.win.getProperties().getXSize() // 2
            centerY = self.win.getProperties().getYSize() // 2

            self.heading -= (x - centerX) * self.mouse_sensitivity
            self.pitch -= (y - centerY) * self.mouse_sensitivity

            # Clamp pitch
            self.pitch = max(-89, min(89, self.pitch))

            # Reset mouse to center
            self.win.movePointer(0, centerX, centerY)

        self.camera.setHpr(self.heading, self.pitch, 0)

        # Movement
        move_vec = Vec3(0, 0, 0)

        if self.keys['w']:
            move_vec.y += 1
        if self.keys['s']:
            move_vec.y -= 1
        if self.keys['a']:
            move_vec.x -= 1
        if self.keys['d']:
            move_vec.x += 1
        if self.keys['space']:
            move_vec.z += 1
        if self.keys['shift']:
            move_vec.z -= 1

        if move_vec.lengthSquared() > 0:
            move_vec.normalize()
            move_vec *= self.move_speed * dt

            # Rotate movement based on heading
            import math
            rad = math.radians(self.heading)
            cos_h = math.cos(rad)
            sin_h = math.sin(rad)

            new_x = move_vec.x * cos_h - move_vec.y * sin_h
            new_y = move_vec.x * sin_h + move_vec.y * cos_h

            self.player_pos.x += new_x
            self.player_pos.y += new_y
            self.player_pos.z += move_vec.z

            self.camera.setPos(self.player_pos)

        return Task.cont

if __name__ == '__main__':
    game = FirstPersonGame()
    game.run()
