#color = ("pink")
color = input("Choose a color:")
noun =input ("Choose a noun:")
plural_noun =input ("Choose a plural noun:")
plural_noun_2 = input("Choose another plural noun:")
person_1 = input("Choose a random character or person:")
person_2 = input("Choose another random character or person:")
verb =input ("Choose a random action verb:")

print("This is ", person_1)
print(person_1 + "s favorite color is", color)
print(person_1 + "s best friend is", person_2)
print("They both like staring at", plural_noun_2)
print(" They also like staring at", noun)
print(" They also slightly look like ",plural_noun)
print(" Hehe,and finally, right now, there are", verb)
