name1 = input("What is the name of your first character?")
color1 = input("Great. now, what color are they?")
print("-----------")
print("1-Superstructure")
print("2-survivors")
print("3-fallen")
align1 = input(f"please select an alignment for {name1}. This will have a minor effect on gameplay.")
print("-----------")
print("1-fighter")
print("2-ranger")
print("3-Alchemist")
print("4-assassin")
print("5-noble")
class1 = input(f"please select a class for {name1}. This will have a major effect on gameplay.")
print("-----------")
print("1-void")
print("2-corruption")
print("3-fallen sun")
print("4-opalescent")
print("5-telepathy")
print("6-gravity")
magic1 = input(f"please select a psychic attunement for {name1}. This will have a major effect on gameplay.")

print(f"--------{name1}--------")
print(f"color:{color1}")