# Make your own mad lib
# Look at sample_1_input_output.py for example statements

# Ask the user for a variety of inputs
noun = input("Enter a noun: ")
plural_noun = input("Enter a plural noun: ")
verb_ending_in_ing = input("Enter a verb ending in ing: ")
Plural_noun = input("Enter a plural noun: ")
city= input("Enter a city: ")
Plural_Noun = input("Enter a plural noun: ")
adjective= input("Enter a adjective: ")
Noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
number = input("Enter a number: ")
NOUN = input("Enter a noun: ")
adjective_1 = input("Enter a adjective: ")
verb_1 = input("Enter a verb: ")
plural_noun_1 = input("Enter a plural noun: ")
verb_ending_in_ing_1 = input("Enter a verb ending in ing: ")
number_1 = input("Enter a number: ")
adverb = input("Enter a adverb: ")
noun_1 = input("Enter a noun: ")
adjective_2 = input("Enter a adjective: ")

# Then print your mad lib using the user input
print("In 1918, the U.S. launched the first real Space ", noun)
print("It was named Columbia and was piloted by two brave ", plural_noun)
print("They practiced", verb_ending_in_ing, "for two years and were expert ", Plural_noun)
print("Columbia took off from", city, "using it's powerful first-stage", Plural_Noun)
print("and soaring off into the", adjective, "blue", Noun, "At an altitude of", number)
print("feet, it went into orbit around the", NOUN)
print("For people watching from Earth, it was a/an", adjective_1, "sight to", verb)
print("Who could really", verb_1, "that there were two", plural_noun_1, "in space?")
print("It was mind", verb_ending_in_ing_1, ". After", number_1, "orbits, the shuttle landing", adverb)
print("at an air force", noun_1, ". It was a/an", adjective_2, "day for the U.S. Space Program.")